site_name: OdiaNLP
strict: false

nav:
  - Purpose: purpose.md
  - Major ongoing projects:
    - Machine Translation:
        - Progress: Machine_Translation/progress.md
        - Ingestion pipeline flow: Machine_Translation/MT_Flow_Pipeline.md
        - Problems:
            - Sentence Alignment: Machine_Translation/sentence_alignment.md
            - UI for corpus generation: ui_for_corpus_generation.md
    - Wishlist: possible_projects.md
  - Blogs:
  - Other Contributions: contributions.md
  - Contributors: contributors.md


theme:
  name: material
  collapse_by_default: true
  highlights: true

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - toc:
      permalink: "#"
