# Website
site_name: OdiaNLP
site_url: https://www.mte2o.com
site_author: Soumendra Kumar Sahoo
site_description: >-
  A website about ongoing progress on NLP(Natural Language Processing) and beyond for Odia language.

# Repository
repo_name: OdiaNLP
repo_url: https://github.com/OdiaNLP/odianlp.github.io

# Copyright
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a> This Website's documentation work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.


# Configuration
theme:
  name: material
  collapse_by_default: true
  highlights: true
  logo: images/logo.png

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - instant
    # - navigation.sections
    - navigation.top
    - navigation.tabs
    - tabs
    - toc.integrate
  palette:
  - scheme: default
    primary: indigo
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    primary: green
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/logo.png

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.tabbed
  - attr_list

# Customization
extra:
  homepage: https://www.mte2o.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OdiaNLP
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/5014656/soumendra?tab=profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/soumendra_ks
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/soumendrakumarsahoo/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

nav:
  - Home: 
    - About: index.md
    - Contributors: contributors.md
    - Purpose: purpose.md
  - Need help: possible_projects.md
  - Projects:
    - Projects: projects.md
    - Machine Translation:
        - Progress: machine_translation/progress.md
        - Architecture:
          - Ingestion pipeline flow: machine_translation/MT_Flow_Pipeline.md
        - Datasets: machine_translation/datasets.md
        - Challenges:
            - Sentence Alignment: machine_translation/sentence_alignment.md
            - UI for corpus generation: machine_translation/ui_for_corpus_generation.md
            - Tweets extraction: machine_translation/tweets_extraction.md
    - Dictionary: dictionary.md
    - Others: contributions.md
  - Resources:
    - Text: resources/text.md
    - Audio: resources/audio.md
    - Visual: resources/visual.md
  - Blogs:
    - Odias in ML: blogs/odias_in_ML.md
  - Newsfeed:
    - Updates: newsfeed/newsfeed.md
